openapi: "3.0.1"
info:
  title: "Music Fella API"
  description: "Endpoint definitions for music fella server"
  version: "0.1"
servers:
  - url: "http://localhost:3434"
paths:
  /v0/add/fella:
    post:
      tags:
        - "Add Fella"
      summary: "Add fella"
      description: "Post a fella to add to the music fella server"
      parameters:
        - name: "artist"
          in: "query"
          description: "artist(s) who produced the fella"
          required: true
          schema: 
            type: "array"
            example: 
              - "oddisee"
            items: 
              type: "string"
        - name: "name"
          in: "query"
          description: "name of fella"
          required: true
          schema:
            type: "string"
            example: "odd cure"
        - name: "type"
          in: "query"
          description: "type of fella"
          required: true
          schema:
            type: "string"
            enum: 
              - "album"
              - "ep"
              - "song"
            example: "album"
        - name: "releaseDate"
          in: "query"
          description: "date fella was released in yyyy-mm-dd format"
          required: true
          schema:
            type: "string"
            format: "date"
            pattern: /([0-9]{4})-([0-9]{2})-([0-9]{2})/
            example: "2020-07-17"
        - name: "features"
          in: "query"
          description: "artist(s) feature on this fella"
          required: false
          schema: 
            type: "array"
            example: 
                - "olivier st.louis"
                - "ralph real"
                - "sainte ezekiel"
                - "priya ragu"
            items: 
              type: "string"
        - name: "country"
          in: "query"
          description: "Country this fella comes from"
          required: false
          schema:
            type: "string"
            example: "usa"
        - name: "genre"
          in: "query"
          description: "Genres/Associated tags to go w/this fella"
          required: false
          schema: 
            type: "array"
            items: 
              type: "string"
            example: 
              - "hip hop"
              - "rap"
              - "washington"
      responses:
        '200':
          description: "OK"
        '201':
          description: "new entry was created"
        '400':
          description: "Bad Request, invalid request syntax"
        '401':
          description: "Unauthorized to make this request"
